// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMhHpAh2zkBMPG-eCGnAIE--NYhqY-I_s',
    appId: '1:104403552010:android:865a200bab0253bedcdcf3',
    messagingSenderId: '104403552010',
    projectId: 'adven-9689e',
    storageBucket: 'adven-9689e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2QS0jW0y5XMLGLY4tlsyU_Dt4RfbhloU',
    appId: '1:104403552010:ios:01619f640fc6e84edcdcf3',
    messagingSenderId: '104403552010',
    projectId: 'adven-9689e',
    storageBucket: 'adven-9689e.firebasestorage.app',
    iosBundleId: 'com.example.adven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2QS0jW0y5XMLGLY4tlsyU_Dt4RfbhloU',
    appId: '1:104403552010:ios:01619f640fc6e84edcdcf3',
    messagingSenderId: '104403552010',
    projectId: 'adven-9689e',
    storageBucket: 'adven-9689e.firebasestorage.app',
    iosBundleId: 'com.example.adven',
  );
}
